### ISSUE TITLE
Non-stable channels which are publicly exposed don't explain risk levels

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#1247]
I've seen a few complaints online about various snaps which are not production quality. On further inspection, the snaps in question are not even available in the stable channel. Normal users, who just want software, and who are not invested in our platform (which is a significant majority of snap users) do not appreciate the risks inherent with non-stable snaps. We do not make it clear that these snaps are not ready for prime-time. Let's take the use case of someone being told there's a copy of steam in the snap store and given this link https://snapcraft.io/steamforwindows (but it also works if they search as it's the first hit).

![image](https://user-images.githubusercontent.com/1841272/47615704-5fb82800-daaa-11e8-8461-5390230b3a0c.png)

Here's the store page. Note I'm picking on a snap *we* (snapcrafters) owns, but this could happen with *any* edge channel snap.

![image](https://user-images.githubusercontent.com/1841272/47615596-bde40b80-daa8-11e8-8c54-9e8654a376fc.png)

I see no install button but a clue is the "All versions" button, which is where I might expect an Install button.

![image](https://user-images.githubusercontent.com/1841272/47615611-d9e7ad00-daa8-11e8-8918-2e669123e5bd.png)

Still no install option, but if I somehow know to hover my mouse over it (which seems obtuse) then I see an "Install >" link. Click that and the UI changes.

![image](https://user-images.githubusercontent.com/1841272/47615626-01d71080-daa9-11e8-8819-e8bbfb9727bd.png)

The description is "latest/edge". In my persona of non-snap advocate and end user, I have *no* *clue* what that means, but "latest" sounds awesome, just what I need!

I have two options. One asks if I want to open the Desktop Store (which doesn't work on KDE Neon 18.04 with the snap-store snap installed, but I'll save that for another bug). 

The other option is to paste a command in a terminal, which I do, because I'm a user and I know no different. 

```
$ sudo snap install steamforwindows --edge
[sudo] password for alan: 
Download snap "steamforwindows" (11) from channel "edge"                            16% 3.75MB/s 30.3s
```

I now have an edge channel, bleeding edge, probably broken snap installed, with nothing explained to me along the way about these risks.

We should absolutely not be pointing normal end users at the edge channel with no details about what their expectations are.

**Comment by matthewpaulthomas** [comment]
[The original rationale](https://forum.snapcraft.io/t/showing-edge-and-beta-in-search-results/4004), for treating all levels equally, was “Some software remains in beta or alpha for a long time, yet people use it widely. The [`stable`-only search] results constraint creates pressure towards mislabeling the software just so people can find it.”

We now have the opposite extreme: even if developers accurately label software as an alpha or beta, that doesn’t protect users at all, because they won’t notice or won’t understand the distinction. [As I wrote in May](https://github.com/CanonicalLtd/snapcraft-design/issues/458): “What does each level mean? The store exists only so that users can install snaps, so the distinction is useful for publishers only if it’s useful for users. There seems to be a general conflict at the moment, between the idea that every snap should have the same four levels (unlike tracks) so that publishers will use them in a way that’s predictable to users, and the idea that all four levels should be treated the same way.”

In other words, as long we don’t distinguish between the levels, users won’t understand why some snaps are poor quality; they’ll just lower their opinion of snaps in general.

There are many ways we could distinguish between snaps of different levels:
- whether the snap has a Store page at all, or is accessible only from the CLI
- if it does have a Store page, whether it shows up in Store search results by default, after clicking some opt-in link, or not at all, and equivalent for Web search results (`<meta name="robots" content="noindex">`)
- how it’s ranked in Store search results (though this would be no help in single-result cases like Steam)
- how the search result is styled or decorated
- how its Store page is styled or decorated
- whether accessing the install instructions requires extra confirmation.

(Another idea, proposed previously, was for the Store page to provide CLI installation instructions that fail to work because they omit the `--`_level-name_ flag. We didn’t do that because it would have seemed like a pothole rather than a speed-bump.)

**Comment by popey** [comment]
This has popped up again. A snap was published in edge which is completely empty. The snap contains only the bare minimum `manifest.yaml`, `snap.yaml` and `snapcraft.yaml`. We were [alerted](https://forum.snapcraft.io/t/open-source-billing/8559) to this on the forum. 

![screenshot from 2018-11-17 23-04-50](https://user-images.githubusercontent.com/1841272/48666630-94256f80-eabd-11e8-9a6b-3100e29ee96b.png)


```
alan@hal:~/Temp/squashfs-root$ tree
.
├── meta
│   └── snap.yaml
└── snap
    ├── manifest.yaml
    └── snapcraft.yaml
```

So we really need to be able to articulate the risk levels to users, but also to developers. The well-meaning developer who has successfully got their snapcraft store publishing workflow sorted before actually packaging the application itself may want to think twice before releasing to edge.

**Comment by lilyvidenova** [comment]
This issue has two parts - the user and the developer; I'm focusing on the user at the moment. Here are three quick proposals for a little message we can add to the Install modal for snaps that are available just on the edge channel: 

![image](https://user-images.githubusercontent.com/17980375/84682652-d7f88900-af2d-11ea-9f2a-ca7ddff9f602.png)

![image](https://user-images.githubusercontent.com/17980375/84682685-ea72c280-af2d-11ea-86b2-27f57ae5bb73.png)

![image](https://user-images.githubusercontent.com/17980375/84682602-c8794000-af2d-11ea-88f4-8551c131f185.png)

In addition I'd like to propose we add a similar message to the Install modal for any snap when the user chooses to install the edge channel:

![image](https://user-images.githubusercontent.com/17980375/84682805-1a21ca80-af2e-11ea-9e6d-df0c662bbf95.png)

**Comment by clagom** [comment]
The message looks like a good first step to implement. I wonder the level of prominence that it needs to have, might fit to the Vanilla info-notification style.
Overall, I think this issue (both consumer and publisher) overlaps nicely with the research @danielmutis started on the charm level for certifications and 'ready for production' charms. Not saying we also need badges here necessarily, but those findings might be useful for the Snap store, too. Maybe you two can sync a bit on the research.

**Comment by lilyvidenova** [comment]
Will do. 
As a first step, I think we can start with the least prominent one:
![Option B](https://user-images.githubusercontent.com/17980375/84761611-92859b80-afc1-11ea-8c48-86ea91d8c0e6.png)

**Comment by Lukewh** [comment]
Would the message be the same for every risk that isn't stable? If there are different tracks would it be displayed if one track has stable, but another doesn't?
```
Channel              Version            Published
latest/edge          1.0.0              date
2.0/stable           2.0.0              date
```

**Comment by lilyvidenova** [comment]
@Lukewh I think we should show the messages as follows:

This message on the first step will only be displayed for snaps that have *only* unstable versions available:
![image](https://user-images.githubusercontent.com/17980375/84773967-1432f480-afd5-11ea-8970-3f717b6682f3.png)

The second message will be displayed on every unstable track (so that'll be on every track except for stable):
![image](https://user-images.githubusercontent.com/17980375/84774083-39276780-afd5-11ea-8135-8ad39815cd8e.png)

**Comment by Lukewh** [comment]
@lilyvidenova :+1: I'll unassigned you and @clagom and work on it

**Comment by lilyvidenova** [comment]
Oh cool, I did make a different one for build - https://github.com/canonical-web-and-design/snapcraft.io/issues/2892 but I'll delete it
