### ISSUE TITLE
Integrate build content into the homepage

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#1278]
Right now we have a build homepage in build.snapcraft.io but we can look at how to drive more users into build just by adding some additional content on the homepage in regards to build.

**Comment by matthewpaulthomas** [comment]
It would be easy to “drive more users into build” by going back to [what we were doing a year ago](http://web.archive.org/web/20171119170605/https://snapcraft.io/): “[ Learn to craft your first snap ] or Auto-build and publish from your GitHub repos”.

We stopped that because (a) it’s asking users to make a choice, when they probably don’t have the necessary knowledge, and (b) we concluded that Build is kinda backward: it tries to get you to automate your snap builds, when you probably don’t even _have_ snap builds yet.

So [in March we planned](https://docs.google.com/document/d/1Bfqpf6XIFo2NY_zLNAfG8nrNpa4M6hMaZqcY1Hvqzd0/edit#heading=h.pvajp8wr709p) to “Subsume build.snapcraft - bringing BSI into snapcraft.io”, once there were publisher pages to access it from. Lyubo’s mockup from January:

![snap details - build rele s - first use 2x copy 2](https://user-images.githubusercontent.com/19801137/48190922-cc011a00-e33b-11e8-98d8-da72a1cc8e0d.png)

This mockup shows “Builds” and “Releases” as separate tabs, but [our testing showed](/CanonicalLtd/snapcraft-design/issues/66#issuecomment-388794357) they were more understandable when combined. So now that the release UI exists, 🎉 we’re ready to use it as the new access point for auto-build settings.

**Comment by therealjuan** [comment]
There is a conversation going on about Travis and how to integrate with snapcraft so would defer this feedback to this work stream.

We need to properly think about how to frame it and a workshop with advocacy might be helpful.

**Comment by therealjuan** [comment]
Thinking out loud we might not need to ask users for a choice and just present the options in the homepage: Learn to craft your first snap / Auto-building from a github repo.

The idea here is not to make a publisher decide which option and then unfold the rest but more into presenting the available journeys and funnel them through a similar experience to the one created with the first-snap flow.

Another entry point will be to map from the Release UI the auto-build part.

**Comment by matthewpaulthomas** [comment]
I understand making a publisher decide on an option, without necessary knowledge, isn’t the intention — but that would still be the basic effect of presenting the two adjacent options on the front page. I think it was Advocacy who originally flagged the problem of Build expecting you to automate builds that probably don’t exist yet, so a workshop with them is a good idea.

Automation doesn’t need to be integrated into snapcraft.io all at once: at any stage the UI could be a mixture of integration and documentation (like the first-snap flow is). For example, we might integrate GitHub first, with the CircleCI and Travis options doing nothing but linking you to the [CircleCI Snap Store reference](https://circleci.com/docs/2.0/build-publish-snap-packages/) or [Travis Snap Store reference](https://docs.travis-ci.com/user/deployment/snaps/). So, that doesn’t need to block on any Travis work.

**Comment by solazio** [comment]
@Lukewh perhaps @danielmutis can look at this if we still want to do it.

**Comment by danielmutis** [comment]
@solazio @Lukewh There was a mock up done for this already [here](https://zpl.io/aR7dgxg).

**Comment by solazio** [comment]
@Lukewh should I implement it?

**Comment by Lukewh** [comment]
I think we should close this and cover it in the snap explain content epic. We should implement everything as one feature. There's also a meeting I'm going to tomorrow about snapcraft.io homepage, so the designs may change yet again
