### ISSUE TITLE
Invalid symbols sequence such as (A B) for token: "-only" at position: 7 

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#1585]
Trying to set GNU GPL 3 only as license on a snap. 

"Invalid symbols sequence such as (A B) for token: "-only" at position: 7 "

![screenshot from 2019-02-13 00-58-50](https://user-images.githubusercontent.com/1841272/52678760-bbf46a00-2f2a-11e9-9464-6692b6db0f89.png)

**Comment by popey** [comment]
There appear to be two licenses with the exact same name. Choose one, you get this error. Choose the other and you don't.

**Comment by Roadmaster** [comment]
Store-side, we only accept SPDX 2.x identifiers (for which the "-only" variants are simply e.g. AGPL-3.0 (not AGPL-3.0-only). "And later" versions are AGPL-3.0+.
The list of valid identifiers is pretty much this one: https://github.com/snapcore/snapd/blob/master/spdx/licenses.go
No component of the snap ecosystem (dashboard, the Store, snapd, snapcraft or the storefront) should move ahead with supporting SPDX 3.x without the other components also doing it, otherwise the list of licenses will not match and we get this kind of problem.

See https://forum.snapcraft.io/t/keeping-up-with-spdx-license-identifier-updates/7095/ for more discussion.

**Comment by tbille** [comment]
Fixed since https://github.com/canonical-web-and-design/snapcraft.io/pull/2448
