### ISSUE TITLE
Unlisted is not shown in the privacy column on https://snapcraft.io/snaps

### ISSUE THREAD

**Issue by evandandrea** [canonical-web-and-design/snapcraft.io#1623]
The privacy column on https://snapcraft.io/snaps erroneously claims that unlisted snaps are public.

**Comment by tbille** [comment]
@evandandrea this is a feature that needs to be added in the store api. I opened an issue for that https://bugs.launchpad.net/snapstore/+bug/1817296

Once implemented we will need to modify our templates to display this information. I am adding you @Lukewh since there is no logic on the backend, I am just proxying all the information to the frontend.
