### ISSUE TITLE
Store front page shows a test edge-only snap

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/snapcraft.io#1624]
1\. Go to [snapcraft.io/store](https://snapcraft.io/store).
2\. Scroll to the “Health & Fitness” section.

What you see: “Señor Limón”, a test snap that is published only in edge.

![snapcraft io-store-test-snap](https://user-images.githubusercontent.com/19801137/53160551-77bb3680-35c8-11e9-8542-03693799b9f7.png)

What you should see: Test snaps should not be promoted on the front page.

One way of solving this would be to exclude snaps from the front page unless they have a stable version (or maybe a stable/beta version).

Another way, now that it is possible to have unlisted snaps, would be to prohibit public listings of snaps that do nothing useful, and add “Snap does nothing useful” as a possible reason for reporting a snap.

**Comment by hughesjordan** [comment]
**So rules should be as follows:**
* Public snaps can appear on front page if they meet the following:
  * They have a beta release or above?
  * They 'do something useful' - how would you propose to define this? They have not yet been reported? @matthewpaulthomas 
- Unlisted snaps never appear on front page
- Private snaps never appear on front page

**When we introduce the new 'first snap flow':**
- snaps pre-fixed with **'test-'** never appear on front page **OR** within search results

**Comment by solazio** [comment]
This doesn't happen anymore - at least with that snap.

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/2af10e09-3169-4661-8e9b-fe30462f7ab0)

However if I search for `lukewh` I can see a number of snaps. Is this the expected behaviour?

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/0d33873f-c325-4fde-8768-9a75bb67cab5)

**Comment by Lukewh** [comment]
Looks accurate now thanks @solazio
