### ISSUE TITLE
Investigate listing repos from Gtihub

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#1870]

**Comment by bartaz** [comment]
GitHub is using JSON-based REST API https://developer.github.com/v3/ so there is probably no need for any specific library. build.snapcraft.io currently simply fetches JSON data from GitHub API.

There are however couple of Python libraries that wrap around GitHub v3 API: https://developer.github.com/v3/libraries/#python

On the other hand it may be worth investigating using new v4 API https://developer.github.com/v4/ that uses GraphQL instead of REST.
This should allow us to batch some of the calls to GitHub and would give us more flexibility in terms of what data we get. We haven't used that yet, so we would need to check if it covers same functionality.
