### ISSUE TITLE
/store some category banners have broken images

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/snapcraft.io#1917]
### Steps to reproduce the problem

Go to /store and scroll down the page. Some categories have broken images. Examples below:
![Screenshot 2019-05-14 at 15.44.57.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b0cac9fc-8270-48b0-96d3-53a7d44a3548)

![Screenshot 2019-05-14 at 15.45.14.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/1a4f22e6-af04-4b6d-b339-9725d649f28a)

**Comment by bartaz** [comment]
@anasereijo Does it still happen to you? Can you share any errors from the browser console?

I think I've seen similar problems the first time I visited this page (after banners were introduced). After reloading the page it all worked fine.

@Lukewh I have suspicion that this may be caused by browser caching maybe? If browser has image cached before it got CORS header it would fail to render it. Only after image is refreshed from server it sends CORS header and is rendered correctly. So, it would be good to at least fall back nicer (in case of JS failing because of cors image still should be rendered and background should be default).

**Comment by therealjuan** [comment]
I can confirm that I got the same error once I opened snapcraft.io for the first time after refreshing it got cleaned up. All errors in console were CORS-related which might suggest @bartaz point.

**Comment by therealjuan** [comment]
This issue was due to caching so now is not happening with the latest fix.
