### ISSUE TITLE
My published snaps - no release for maas snap

### ISSUE THREAD

**Issue by albertodonato** [canonical-web-and-design/snapcraft.io#1977]
### Expected behaviour

The row for the `maas` snap shows the latest released version

### Steps to reproduce the problem

When I log in and go and access `https://snapcraft.io/snaps` I see this: https://i.imgur.com/kg3dvFB.png

### Specs

- _URL:_ https://snapcraft.io/snaps
- _Operating system:_ Ubuntu 19.04
- _Browser:_ Chromium

**Comment by cprov** [comment]
This problem seems to be related to the fact all the latest revisions are queued for review:

![image](https://user-images.githubusercontent.com/3610997/59102177-b5d33080-8901-11e9-9c88-8445ab581331.png)

Thus, the account-info `.snaps["16"]["maas"].latest_revisions[]` set does not contain any `Published` entry and their `channels` is empty.

This situation, a set of new revisions waiting for review, is not rare and will happen every time a snap requests a special interface or capability. I think the UI assumption ('not released') is inferring too much from the `latest_revisions` field.

**Comment by albertodonato** [comment]
This is now fixed, thanks
