### ISSUE TITLE
"Snap is not ready to be published" with no indication why

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2031]
### Expected behaviour
When promoting a new build to a channel, if the snap is not ready to be published, there should be some indication _why_ this is the case and how to fix it.

### Steps to reproduce the problem
I have a new snap, `magnus`, built with build.snapcraft.io from a github repository. I have completed the listing page, and the build has also completed; when I try to promote this new build to edge (which is the first promotion; the snap has not yet been published), the website shows the error:

Error:Error while releasing 1.0.1-ef41eb2 (4) to latest/edge. Snap is not ready to be published.

As far as I can tell, there is no indication anywhere about _why_ the snap is not ready to be published or how I might rectify that.

### Specs

- _URL:_ https://snapcraft.io/magnus/releases
- _Operating system:_ Ubuntu 18.04
- _Browser:_ Firefox

![image](https://user-images.githubusercontent.com/4356350/59854656-39ae0380-936b-11e9-82b2-d5603cf3fe64.png)

**Comment by stuartlangridge** [comment]
Note: I have since received an email which points to a manual review being required at https://dashboard.snapcraft.io/snaps/magnus/revisions/1/. It's fine if my snap can't be published or promoted until it passes manual review, but I would suggest that the "error" message should then say something like:

This snap cannot be published because it is still pending a manual review. See the manual review _here_ or under the "pending reviews" tab.

As far as I can tell, that review page isn't linked from anywhere in my snapcraft.io UI -- the email is the only place which mentions it. Shouldn't there be a "reviews pending" tab somewhere? (and the error message can link directly to the review for convenience as well, but allowing me to see that this review exists is the important part.)

**Comment by iainlane** [comment]
The UI here has changed and now I think if anything it's slightly more confusing. I built a new snap using build.snapcraft.io and was trying to release it to edge. I didn't realise at the time but since this is a classic snap it requires manual review. (Like @stuartlangridge I found out about that the next time I looked at email.)

When trying to release to edge the "Save" button goes insensitive and nothing ever happens (sorry for this poor gif):

![output](https://user-images.githubusercontent.com/321014/76742589-36fd0500-6769-11ea-844b-7b63ffafe054.gif)

I'd have liked it I think if this page explained to me that I was going to have to wait for a review, rather than presenting the revision as something that could be manipulated.

**Comment by Lukewh** [comment]
If you go to https://dashboard.snapcraft.io/snaps/snap_name do the list of revisions in the left hand column have "!"'s next to them? If you click on one of those revisions what information do you get? I believe this to be an issue that we're not displaying the status of revisions in snapcraft.io, but want to confirm it's not something else - thanks.

**Comment by iainlane** [comment]
For me it looks like this:

![revisions](https://user-images.githubusercontent.com/321014/77064717-eccd8b00-69d7-11ea-8f67-d8c31e108fdc.png)

If I click into them the status of 1 is "Manual review pending" and the others are "Review queued" but there's a banner at the top "Revision waiting for review of a previous upload: revision #1".

**Comment by Lukewh** [comment]
@iainlane thanks, it's what I thought. I'll work on fixing this :+1:
