### ISSUE TITLE
Release UI: Merge promote and close channel options into one

### ISSUE THREAD

**Issue by therealjuan** [canonical-web-and-design/snapcraft.io#2035]
As a preamp of fully moving to the Release UI using drag and drop, we would like to combine the options to promote to channels and close channel under one element:

![image.png](https://images.zenhubusercontent.com/56b0a0916caf56c9d38c2685/66ea2a47-c91b-4dc5-965d-4bec7c51ce67)

The icon that we want to use is this one: ![ Settings.svg](https://images.zenhubusercontent.com/56b0a0916caf56c9d38c2685/e2bbf3cd-f736-4fb2-957c-cb1eddc3a041)

The icon can be found [here](https://assets.ubuntu.com/v1/4bdf3576-Settings.svg)

**Comment by therealjuan** [comment]
Just been fixing up the icons...

We would like to use this one to indicate [dragging](https://assets.ubuntu.com/v1/a454e5e3-p-icon--draggable.svg)

![image](https://user-images.githubusercontent.com/8167677/60029409-00da9b00-9699-11e9-8060-774fdd9158c7.png)

... and look for options between these two icons:

[a) One vertical set of 3 dots inspired in Material design](https://assets.ubuntu.com/v1/6b189747-p-icon--options.svg)

![image](https://user-images.githubusercontent.com/8167677/60029481-223b8700-9699-11e9-95a4-55eea40b5d0e.png)

[b) Inverted 3 dots](https://assets.ubuntu.com/v1/c8dce007-p-icon--more.svg)

![image](https://user-images.githubusercontent.com/8167677/60029486-25367780-9699-11e9-93ac-4b78df92b861.png)

Would be great if you could add both and we could see the difference and see which one works better.

**Comment by bartaz** [comment]
@therealjuan I think the icons are bit too small:

<img width="1032" alt="Screenshot 2019-06-25 at 09 04 20" src="https://user-images.githubusercontent.com/83575/60076691-822d3e80-9728-11e9-9158-b1a694302584.png">
<img width="1033" alt="Screenshot 2019-06-25 at 09 04 37" src="https://user-images.githubusercontent.com/83575/60076694-822d3e80-9728-11e9-98f2-1b2713801e88.png">
<img width="1050" alt="Screenshot 2019-06-25 at 09 04 58" src="https://user-images.githubusercontent.com/83575/60076696-822d3e80-9728-11e9-92da-ec067ca352d2.png">

It seems to be because SVG size is 26x26 pixels, but the icon itself inside is smaller (with margin around).
So when put into Vanilla it gets scaled down to 16x16px making the icon even smaller in the middle.
I think the icon itself should take as much of the full SVG square as possible, so it's size is 16px when put into Vanilla.
<img width="119" alt="Screenshot 2019-06-25 at 09 05 29" src="https://user-images.githubusercontent.com/83575/60076697-822d3e80-9728-11e9-8657-a2127edf0c36.png">

You can check the icons on demo:
https://snapcraft-io-canonical-web-and-design-pr-2036.run.demo.haus/nextcloud/releases#1
https://snapcraft-io-canonical-web-and-design-pr-2036.run.demo.haus/nextcloud/releases#2
https://snapcraft-io-canonical-web-and-design-pr-2036.run.demo.haus/nextcloud/releases#3
(to change icon put `#1` `#2` `#3` in url - but make sure to reload the page)
