### ISSUE TITLE
Consult drag handle icon with design

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/snapcraft.io#2071]
@spencerbygraves Mentioned that we should review our drag handle icon to make it consistent with other Canonical icons.

**Comment by spencerbygraves** [comment]
Thanks @bartaz we have an agency that will be designing a new set of icons for us. if you ever have any requests we can send them over.

**Comment by therealjuan** [comment]
Closing as unclear objective of this task

**Comment by spencerbygraves** [comment]
@therealjuan this issue was probably a bit early.

The icons we have are being updated soon, we should change them in all products when we have a new set.

Cheers.

**Comment by therealjuan** [comment]
Sure no problem, but we only want to keep track of work to be done and since the bulk of this work is not needed for the squad, as we are outsourcing from what it seems without knowing what would be the set because items like branches or history might not be part of the icon set hence why we did our own.

**Comment by spencerbygraves** [comment]
You'll be able to request any icons you need in the future, as it's an ongoing relationship, not a one time definitive set.
