### ISSUE TITLE
Metrics: Investigate Publisher snap metrics page

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/snapcraft.io#2243]
## Publisher snap metrics page
- [x] Area chart with tooltip on hover + annotations overlay (for categories) - Horizontal
- [x] "Territories" World map with tooltip on hover (actual numbers)

**Comment by kwm14** [comment]
## Review
_with @hughesjordan_ 

**New chart proposal**
- Worth exploring visual
- Explore a test case of (Filter by Past year and OS)

**Map chart**
- +1
- Test case a snap with lots of territories to see how it will scale
- The horizontal bar chart has some legs

**Comment by kwm14** [comment]
## Map chart
Further exploration based on feedback in reviews.

### Data table
- Table to show active users per country
- Giving the user quickly visibility of numbers
- Example with low and high territories

![Territories 001](https://user-images.githubusercontent.com/17748020/65590930-849b7080-df83-11e9-90ee-0773b08983fb.png)

![Territories 002](https://user-images.githubusercontent.com/17748020/65590932-85340700-df83-11e9-9cb5-110ceb897b2b.png)

### Horizontal bar chart
- Bar chart displaying the percentage of active devices per country
  - Percentage values change depending on number pf territories
- Keep tooltip on hover per country to also show number of active devices
- Example with low and high territories

![Territories 001a](https://user-images.githubusercontent.com/17748020/65591208-f673ba00-df83-11e9-8ebb-321194def209.png)

![Territories 002a](https://user-images.githubusercontent.com/17748020/65591211-f673ba00-df83-11e9-8ba9-633f3442ab7a.png)

@hughesjordan what do you think based on our discussion yesterday?

**Comment by hughesjordan** [comment]
@kwm14 at the moment I prefer the horizontal bar chart, it allows the user to quickly understand the rough percentage of users in a specific country. In a way it offers the best of both worlds.

Just thinking that a percentage may be more useful than an exact figure?

Could even hover over the bars to get the exact percentage in a tooltip, otherwise another idea could be the table with the percentages in.

**Comment by kwm14** [comment]
> @kwm14 at the moment I prefer the horizontal bar chart, it allows the user to quickly understand the rough percentage of users in a specific country. In a way, it offers the best of both worlds.

Horizontal is my preferred choice too 😉 

> Just thinking that a percentage may be more useful than an exact figure?

I will update so that the tooltip shows the percentage rather than the number 👍

**Comment by hughesjordan** [comment]
@kwm14 ah sorry, I meant in comparison to the data table.

In your second design you get the percentage from the bar chart and the exact figure from the map - that's quite nice.

**Comment by kwm14** [comment]
## Bar chart
Further exploration based on [new proposal](https://github.com/canonical-web-and-design/snapcraft.io/issues/2243#issuecomment-530873216) and reviews, two versions showing high and low traffic.

Obviously this is mocked up in Sketch, using real data will give us a better sense of the metrics displayed 👍 

### High traffic
- Past year/By OS

![Weekly active devices 001](https://user-images.githubusercontent.com/17748020/65703949-8ea19a00-e07d-11e9-94da-cb108ff3f12e.png)

### Low traffic
- Past 30days/By version

![Weekly active devices 001a](https://user-images.githubusercontent.com/17748020/65703959-92352100-e07d-11e9-85b0-1708069fae29.png)

@hughesjordan would be great to get you 👀 on this too 👍

**Comment by hughesjordan** [comment]
@kwm14 I think as an alternative this looks good 👍

I think it makes it easier to tell what month/day you are looking at rather than having to use the mouse and tooltip. However, we lose the slopes on the current graph which indicate the uptake of a new version.

I think it's hard to tell which will be more useful to our users!

**Comment by Lukewh** [comment]
> However, we lose the slopes on the current graph which indicate the uptake of a new version.

This is true for the 7 day window on our current graphs. Longer periods would still make trends visible - I would think?

**Comment by kwm14** [comment]
> @kwm14 I think as an alternative this looks good 👍

Nice one! Can I get a +1 😉 

> However, we lose the slopes on the current graph which indicate the uptake of a new version.

Interesting point, but this is a mockup and I think with real data you would be able to see a trendline across longer periods as @Lukewh mentioned above.

**Comment by hughesjordan** [comment]
When viewing by 'Past year' and by 'Version', in the example above there are only twelve points of reference, one each month. Whereas currently the graph plots metrics from every 7 days.

I was just wondering if presenting more data in this way offers any additional value to a publisher? (Guessing this is based on snap refreshes though? Do they care?)

**Comment by kwm14** [comment]
> When viewing by 'Past year' and by 'Version', in the example above there are only twelve points of reference, one each month. Whereas currently, the graph plots metrics from every 7 days.

Fair point. We could try this when we pick the graph to see how it scales. Google does something similar across a year and plots weekly bars, but becomes very noisy...definitely worth investigating when we come to implement edge cases and what users want to see.

<img width="661" alt="Screenshot 2019-09-30 at 15 48 12" src="https://user-images.githubusercontent.com/17748020/65889825-cf5d2400-e399-11e9-916d-23cfbbd06576.png">

**Comment by Lukewh** [comment]
FYI, when we get to yearly stats the API reduces the number of data points. For snaps with many versions/OSes a years worth of daily data is 365 * [number of versions/OSes] which is a big performance hit (because of the way we currently load the data). Even on a popular snap now, that the buckets are reduced to monthly, the page is timing out when trying to view a year.

This doesn't mean that we can't change the implementation to provide better graphs :)!

**Comment by kwm14** [comment]
## Next steps
Work to be carried out next cycle 20.04.
- Update sparkline to the bar chart
- Add a key below the graph to show version, OS and channel
- Remove color ket from tooltip and align data-title (left) and data value (right) rather than being center aligned

![Weekly active devices 001](https://user-images.githubusercontent.com/17748020/65703949-8ea19a00-e07d-11e9-94da-cb108ff3f12e.png)

**Comment by matthewpaulthomas** [comment]
> The goal is to see the number of active devices between individual categories currently, I think the stacked area chart isn't presenting the data well...

I agree the stacked area chart presents the data poorly at the moment. I can fill in your mysterious dots with two specific explanations: the segment ordering makes trends needlessly difficult to see (#732), and the lack of labelling on large segments makes it harder to tell which segment is which (#331).

> Bar and column charts are one of the most frequently used chart types. They are simple to understand and their visual structure matches the structure of a lot of data.

But they do not match the structure of _this_ data, because active devices over time is a [continuous variable](https://en.wikipedia.org/wiki/Continuous_or_discrete_variable#Continuous_variable): interpolating between two values — for example, the number of devices at 9am and the number at 3pm — is a valid thing to do, and it’s easier to do if a line is drawn between those two values. In contrast, something like installs per day is a discrete variable: for example, if there were 15 installs yesterday and 17 today, they should be shown as separate bars so that if I want the count for the past two days I can eyeball a rough estimate from the chart.

This is why continuous variables over time are generally drawn as line or area charts, while discrete variables are generally drawn as bar charts. It’s _possible_ to present continuous data using a bar chart: for example, [Apple uses a bar chart for Active Devices](https://developer.apple.com/app-store-connect/analytics/), even though it’s a continuous variable, I guess because they think it would look odd to have one line chart surrounded by seven bar charts. But our chart stands on its own, and unlike Apple, we’re showing multiple series on it, which would be needlessly difficult to follow as a bar chart.

> this is a mockup and I think with real data you would be able to see a trendline across longer periods

Maybe, but why have such low expectations? You should be able to see short-term trends too! You often can’t at the moment because of the two issues above, but both of them would be made _worse_ by switching to stacked bars. The ordering problem would be made worse, because the bar segments for little-used versions would sometimes be completely disconnected from the same versions on previous/following days. And the labelling problem would be made a bit worse, because if the bars were separate any labels would be duplicated or separated from much of the area, and even if the bars were touching (as in the Google example above) the [Snake](https://www.ecosia.org/images?q=snake+game)-like area edges would leave room for labelling fewer areas.

I strongly encourage you to just fix the 🤬 bugs rather than switching to a chart type that makes them worse.
