### ISSUE TITLE
#docs Text wrap width is narrower than table and code width

### ISSUE THREAD

**Issue by degville** [canonical-web-and-design/snapcraft.io#2312]
Normal text will often wrap before the width of code and table blocks, which doesn't look aligned and optimal in my opinion.

This from https://snapcraft.io/docs:

![Screenshot_20191016_135102](https://user-images.githubusercontent.com/7047542/66920832-fe22fd80-f01b-11e9-9ec1-9a657db85b12.png)

Another example from https://snapcraft.io/docs/installing-snap-on-red-hat:

![Screenshot_20191016_135224](https://user-images.githubusercontent.com/7047542/66920957-2f9bc900-f01c-11e9-81bd-d587c5e2c3d5.png)

**Comment by Lukewh** [comment]
It's true we have overrides however the Vanilla default for paragraphs is 40em.

I've created a PR to override paragraph widths in docs pages: https://github.com/canonical-web-and-design/snapcraft.io/pull/2316

**Comment by matthewpaulthomas** [comment]
> however the Vanilla default for paragraphs is 40em

Huh, you’re right. I was going by docs.vanillaframework.io, which specifies 52em. I see that the rest of vanillaframework.io specifies 40em. Weird.

**Comment by bartaz** [comment]
> Huh, you’re right. I was going by docs.vanillaframework.io, which specifies 52em. I see that the rest of vanillaframework.io specifies 40em. Weird.

Apparently even for them 40em was to narrow ;)

**Comment by lyubomir-popov** [comment]
There are reasons for limiting the max-width of text elements. What is clearly missing is an explanation in the vanilla documentation to which we can point anyone raising a duplicate issue on the subject. I've created an [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/2586) to address that.

In the meantime, some background:
- The default paragraphs max-width is 40em. 

- 52em is a local docs patch aimed at alleviating what is essentially a markup generator issue - doc generators wrap iframes (and almost anything else) in ```<p>```'s which is neither semantic, nor recommended. Since we don't have control over those generators, we've had to provide a patch in docs. 

Unlike the 40em value inside vanilla, the 52em value is done purely as a patch and is not a design choice.
