### ISSUE TITLE
Godot's official snap doesn't show in site search, but it is accessible via google, etc

### ISSUE THREAD

**Issue by arcooke** [canonical-web-and-design/snapcraft.io#2396]
Go here: https://snapcraft.io/search?q=godot

Godot is not found, but it exists here: https://snapcraft.io/godot

The only way I can find it is through a google search.  Snapcraft search returns a result that looks like a test release or something, with a description of "blah" (https://snapcraft.io/godot-3-1), but not the official snap package.

### Expected behaviour
https://snapcraft.io/godot snap should show up in search results

### Steps to reproduce the problem

1. https://snapcraft.io/search?q=godot 

2. <img src="https://i.imgur.com/e1IneGq.gif" width="150">

### Specs

- _URL:_ https://snapcraft.io/search?q=godot
- _Operating system:_ Solus
- _Browser:_ Firefox

**Comment by bartaz** [comment]
@arcooke Thanks for the report. You are correct. Godot snap doesn't show up in snapcraft search, because its publisher set snap's privacy settings to 'Unlisted' meaning it's removed from snapcraft search results.

<img width="710" alt="Screenshot 2019-12-11 at 22 09 13" src="https://user-images.githubusercontent.com/83575/70660643-ffab2380-1c62-11ea-8b22-7a386dae19bf.png">

This doesn't prevent external search engines from indexing the page. That's why it shows up in Google.

I think you have a valid point and probably 'Unlisted' snaps' details pages should include some metadata to make sure they are not indexed by search engines, as this is what may be expected by publishers (by "does not appear in search results").

![68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f784c705231537936756f53454f773d3d2d3436323835393338322e313464663566363166346362323261363836383030353733363437382e676966](https://user-images.githubusercontent.com/83575/70660936-8102b600-1c63-11ea-9a46-9b9b09aaba9f.gif)

**Comment by arcooke** [comment]
![](https://media1.tenor.com/images/2c6586c17da4615eda7cc95a9b3ec859/tenor.gif)

Gotcha, I had a feeling something like that might be the case.  Might not hurt to show users they are viewing an unlisted snap to avoid any confusion, similar to how Youtube does it:

![](https://i.imgur.com/VOvdyks.png)

Thanks for the info!

**Comment by Lukewh** [comment]
Currently blocked on a field being exposed by the API https://bugs.launchpad.net/snapstore/+bug/1856591
