### ISSUE TITLE
Register snap name button should be enabled

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/snapcraft.io#2399]
### Expected behaviour
The `Register snap name` button should be enabled

![image](https://user-images.githubusercontent.com/40214246/70899659-f9180580-1fee-11ea-81d1-b14b99454d53.png)

### Steps to reproduce the problem

1. Create a new snap
2. When you get to the `Register your snap name` page see the `Register snap name` button is disabled, but actually it should be enabled

### Additional info
As mentioned in IRC, this is likely legacy code. In the first interations of First Snap Flow we didn't autopopulate fields with snap name chosen by user, so we required an edit of the name before registering.

Currently the name is chosen at the beginning and likely doesn't need to be edited.
Also at the same time the warning notification below the input can be removed or changed.
The name will be the same (because it's autopopulated). Maybe we should show the warning if user changes the name.

Or, maybe we don't need the input at all? Maybe it should just be the 'Register your-snap-name name`?

**Comment by bartaz** [comment]
As mentioned in IRC, this is likely legacy code. In the first interations of First Snap Flow we didn't autopopulate fields with snap name chosen by user, so we required an edit of the name before registering.

Currently the name is chosen at the beginning and likely doesn't need to be edited.
Also at the same time the warning notification below the input can be removed or changed.
The name will be the same (because it's autopopulated). Maybe we should show the warning if user changes the name.

Or, maybe we don't need the input at all? Maybe it should just be the 'Register `your-snap-name` name`?
