### ISSUE TITLE
unexpected user switching

### ISSUE THREAD

**Issue by jamesbeedy** [canonical-web-and-design/snapcraft.io#2408]
### Expected behaviour
I expect my omnivector-solutions user to be able to access the build page.

### Steps to reproduce the problem
1) I go here https://imgur.com/a/HfjbnBJ
you can see I'm logged in with my omnivector-solutions user.

2) Click the sign in with github button and am re-logged in to another user.
Seems to login my jamesbeedy user https://imgur.com/a/lwQZ6Hk when the github login link is clicked.

### Specs

- _URL:_ https://snapcraft.io/build
- _Operating system:_ osx/ubuntu
- _Browser:_ chrome

**Comment by Lukewh** [comment]
Hi @jamesbeedy the issue here is that build.snapcraft.io and snapcraft.io are different services, that we've tried to unify, visually.
At step 1. The omnivector-solutions user is a snapcraft.io user (Ubuntu SSO).
When you click "sign in with github" you are forwarded to build.snapcraft.io which exclusively uses github for auth and has no idea you're already logged in to snapcraft.io - and will use whichever github account you're signed in to.

We've done preliminary investigations and will be pulling build.snapcraft.io functionality into snapcraft.io soon - which will solve the issue.

**Comment by solazio** [comment]
This functionality has now been migrated to snapcraft.io
