### ISSUE TITLE
Github Webhooks aren't working against snapcraft.io webhook url

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2578]
### Expected behaviour
When pushing an update to Github, the webhook fails.

### Steps to reproduce the problem
Have a snap using the new snapcraft app - push an update.

![Screenshot_2020-02-27 Lukewh -test-snap-lukewh-2](https://user-images.githubusercontent.com/479384/75471989-cbeeb880-598a-11ea-8259-1b7be4175787.png)

### Specs

- _URL:_
- _Operating system:_
- _Browser:_

**Comment by jkfran** [comment]
This is difficult to check now without the feature being active.

![Screenshot from 2020-02-28 12-03-16](https://user-images.githubusercontent.com/6353928/75547296-77971780-5a22-11ea-9027-67508823ed90.png)

I can also see that your request was done during this period where GitHub was down. All the failing ones that have are 404 wich is normal because the feature is not active.
