### ISSUE TITLE
No logs available for failed builds

### ISSUE THREAD

**Issue by diddledan** [canonical-web-and-design/snapcraft.io#2633]
### Expected behaviour
Should be able to access and review logs of failed builds.

### Steps to reproduce the problem
Navigate to either https://snapcraft.io/stars/builds/865092 or https://snapcraft.io/superperms/builds/865085 and see the logs aren't there.

### Specs

- _URL:_ https://snapcraft.io/stars/builds/865092 and https://snapcraft.io/superperms/builds/865085
- _Operating system:_ Ubuntu 20.04
- _Browser:_ Firefox 74.0 (from Ubuntu apt repo)

### Screenshots
![image](https://user-images.githubusercontent.com/147548/77552423-6c150000-6eab-11ea-95bd-80d1d611be02.png)
![image](https://user-images.githubusercontent.com/147548/77552432-70411d80-6eab-11ea-86ca-6390181a5f2e.png)

**Comment by jkfran** [comment]
Hello @diddledan 

We currently provide the logs for failed builds. After investigating this case looks like the process failed even before the build process started and this is why we don't have the build logs to show.

The solution to this problem is very likely to trigger a new build manually.

Thank you!
