### ISSUE TITLE
Consider redirecting old build.snapcraft.io webhook URLs to new webhook URLs

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-web-and-design/snapcraft.io#2699]
### Expected behaviour

Every snap maintainer doesn't have to edit their github repositories to change the webhook URLs as per https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos, because the old build.snapcraft.io webhook URLs redirect to the new snapcraft.io webhook URLs on the server. Also, because [Cool URIs don't change](https://www.w3.org/Provider/Style/URI), of course :-)

**Comment by jkfran** [comment]
I think we can close as it has been a while and most users already updated theirs webhooks. Thank you.

**Comment by jkfran** [comment]
My previous comment wasn't a good explanation for closing this issue.

First of all, old webhooks URLs are supported and will continue to be. We can't redirect a webhook URL to another URL because it is a POST HTTP request, so it is not technically possible to do it.

The only thing we can do is to continue supporting the previous webhook URL, even if only a few people are using it. We checked the numbers a few times with the Advocacy team to help people switch to the new webhook and the last time we checked we couldn't find anyone using it for 2 months.

I would like to mention as well that if you have trouble setting up your webhook or if you remove it, we added not long ago a new button to set up just the webhook for you automatically:
![image](https://user-images.githubusercontent.com/6353928/139857164-500684e3-93b6-4e95-b6db-14d3ba857eae.png)
