### ISSUE TITLE
The release page doesn't communicate clearly the need to save changes

### ISSUE THREAD

**Issue by seb128** [canonical-web-and-design/snapcraft.io#2760]
I tried to close the edge channel from https://snapcraft.io/thunderbird/releases , after picking the after the revision was replaced by a label 'close channel' stating on mouseover 'pending channel close'

Then I closed the page to come back later seeing the changes were not applied, after talking to the store channel on IRC it seems the Ui confused me

The things that confused me

- 'close channel' was not clear to me, would have been cleared if it had stated 'will close channel' or 'channel closing pending' or something similar

- the mouseover tooltip could hint that there is a save button to press

- closing the page could have prompted for 'pending changes are about to be discarded, are you sure'

Cheers,

**Comment by kubiko** [comment]
Attempt to close channel for situation when we have following architectures,
`amd64` `arm64` `armhf` `i386` `ppc64el` `s390x`
with no revision in stable channel for `ppc64el` `s390x`
Closing candidate channel will close it only for `amd64` `arm64` `armhf` `i386` architectures.

**Comment by lilyvidenova** [comment]
The Store team is aware of the issue with closing channels and is going to investigate.

**Comment by lilyvidenova** [comment]
I think we can, indeed, slightly tweak the wording and make it clearer what's required in order to close a channel.
![Close channel tooltip](https://user-images.githubusercontent.com/17980375/100375544-dfa47980-3005-11eb-9ff3-64eb7a50951d.png)

Also, adding an alert when there are unsaved changes - it could be annoying if you indeed know you didn't want to commit the changes but IMO is useful.
![When navigating away](https://user-images.githubusercontent.com/17980375/100375547-e03d1000-3005-11eb-831c-b2c8ac40f7c2.png)

[Wireframes on Zeplin](https://app.zeplin.io/project/5f919b120352528a2016fe86/dashboard?seid=5fbfda80334eb501ce99b87d)

**Comment by clagom** [comment]
Thanks @lilyvidenova I think both are good ideas. Please check also with @danielmutis as we did user testing on the release UI and there were interesting findings. There might be something else related to this particular aspect.

**Comment by lilyvidenova** [comment]
@danielmutis - shall we have a little call tomorrow?

**Comment by danielmutis** [comment]
Just saw this now. @lilyvidenova let's discuss today in work together. I think the only thing we had from user testing in relation to this is to make the [save bar sticky](https://zpl.io/V48wNQ8) so that it is visible at all times. Apart from that, this seems like a good idea.

**Comment by lilyvidenova** [comment]
+1 on making the save bar sticky and showing it only once there has been a change (however keeping it to the top where it is) 

I think this is now ready do build :)
