### ISSUE TITLE
Tour - accordion instructions are still clickable

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2793]
You can click on the requirements accordion when in the tour .

**Comment by anasereijo** [comment]
Currently, whilst in the tour mode, we keep out of the "overlay mask" the accordion links to 'Hide icon restrictions' and 'show supported markdown syntax'. We should do the same for 'Show image restrictions' and 'Show banner restrictions'. See below:

**how it looks like:**

![Screenshot 2021-11-19 at 14.57.52.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/1bd8e1bd-e840-4973-83bb-ccc977c365e9)

**how it should look like:**

![Screenshot 2021-11-19 at 15.01.20.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/b4c50734-0cc1-4882-a470-78b9d1d6c5b9)

**Comment by bartaz** [comment]
Right now anything in 'visible' box is interactive, because this window doesn't cover the page. So it means "Add banner" can be clicked for example, or text can be entered into text fields.

Do we want it during the tour?
Maybe it would be better for those visible elements to be covered by transparent overlay, so they are in visible 'box', but can't be interacted with?

**Comment by anasereijo** [comment]
@bartaz that's a great idea! I just assumed that it wasn't possible to remove the interactions from those elements while on tour.
