### ISSUE TITLE
Unable to login to build.snapcraft.io

### ISSUE THREAD

**Issue by r-arek** [canonical-web-and-design/snapcraft.io#3032]
### Expected behaviour
Login to https://build.snapcraft.io without any issues

### Steps to reproduce the problem
- Go to the any url under https://build.snapcraft.io
- Page displays message "Your session has expired. Reload the page and sign in again."
- Click "Reload the page" button
- You will be redirected to github oauth
- Github throws 404

Tried the same steps in incognito window, but without luck. 
 
### Specs
- _URL: https://build.snapcraft.io/user/travis-ci/worker/1077513
- _Operating system: macOS
- _Browser: Firefox 80.0 (64-bit)

**Comment by jkfran** [comment]
Hello @r-arek ,

All the URLs for build.snapcraft.io should redirect to https://snapcraft.io/build. I will investigate because currently, only the index page is redirecting.

Please read the following blog article where we explain why build.snapcraft.io is redirecting to snapcraft.io:
https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos

Thank you!

**Comment by r-arek** [comment]
Hi @jkfran,
How can I access builds (travis-ci org) from url mentioned above using the snapcraft.io? I'm member of travis-ci on github, and had access to builds before url was redirected.

**Comment by jkfran** [comment]
Hi @r-arek, you'll have to:

1. Log in on snapcraft.io
2. Go to https://snapcraft.io/snaps
3. Find the snap you are interested in and then click on the "Builds" tab.
