### ISSUE TITLE
 Weekly active devices != Total Number of users in map 

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/snapcraft.io#306]
In publisher metrics page there is little difference between the number of Weekly active devices and the ttal number of users in the map:

- Weekly active devices in the sum of every users in all channels
- Map displays only the number of users in the stable channel.

(on a small snap it looks strange)

**Comment by matthewpaulthomas** [comment]
One of [the intended segmentation options for “Weekly active devices”](https://docs.google.com/document/d/1PQzECKRrVZ-y3W7DcdkfeZipBVr5Xl2mpMj5Vqhux2E/edit#heading=h.rtb5soqn673v) is “by risk level”. This is because it’s important to know, for example, what percentage of your users will be affected by a bug that makes it as far as “beta” before it’s fixed. It may influence your QA processes, or the way you advertise the various channels to users, or both.

For that reason, I think “Weekly active devices” should continue including all channels. Therefore, for consistency, the map should include all channels too.

**Comment by Lukewh** [comment]
@tbille is this an API error or the call that's been made to the API?

**Comment by tbille** [comment]
This issue seems fixed.
