### ISSUE TITLE
It shows blank for some text files

### ISSUE THREAD

**Issue by bigbellmercy** [canonical-web-and-design/snapcraft.io#3073]
### Expected behaviour
The text should appears on the window for some text files on root folders, that can be shown by gedit app.

### Steps to reproduce the problem
Just open some text files in some root folders.

### Specs
- _Operating system:_ Ubuntu 18.04 in Jetson Nano
- _Text editor:_ It was installed by 'Software' app installed in Ubuntu 18.04 in Jetson Nano.

### The error was:
(gedit:15349): GLib-GIO-CRITICAL **: 14:27:59.237: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

or

(gedit:13867): Tepl-WARNING **: 14:13:49.920: GVfs metadata is not supported. Fallback to TeplMetadataManager. Either GVfs is not correctly installed or GVfs metadata are not supported on this platform. In the latter case, you should configure Tepl with --disable-gvfs-metadata.

**Comment by tbille** [comment]
Hi,

thanks for reporting this issue.
This repo is for the website snapcraft.io. If this issue is related to gedit I suggest opening an issue [here](https://bugs.launchpad.net/ubuntu/+source/gedit/+bugs?field.tag=snap). If you think it's snaps related I suggest engaging the discussion on the [forum directly](https://forum.snapcraft.io)

Closing this issue.
