### ISSUE TITLE
Review other shops 

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/snapcraft.io#3184]
How do other popular software shops allow users to see the source code of an application?

**Comment by lilyvidenova** [comment]
Looking at the snaps on s.io some publishers are providing direct links to their github repos: 
<img width="1680" alt="Screenshot 2020-11-24 at 16 12 39" src="https://user-images.githubusercontent.com/17980375/100126585-092e9b00-2e76-11eb-8acf-3de76c17bc57.png">
<img width="1680" alt="Screenshot 2020-11-24 at 16 16 36" src="https://user-images.githubusercontent.com/17980375/100126614-13509980-2e76-11eb-83f3-8144005e60a4.png">

Or links to their website that have links to either directly download the code or pointing at gh:
<img width="1680" alt="Screenshot 2020-11-24 at 16 33 16" src="https://user-images.githubusercontent.com/17980375/100126869-688cab00-2e76-11eb-9a31-662966ed2fd4.png">
<img width="1680" alt="Screenshot 2020-11-24 at 16 15 07" src="https://user-images.githubusercontent.com/17980375/100126906-73474000-2e76-11eb-9b8a-77cd6deda357.png">
<img width="1680" alt="Screenshot 2020-11-24 at 16 15 38" src="https://user-images.githubusercontent.com/17980375/100126971-865a1000-2e76-11eb-8723-1785208b56f1.png">

flathub doesn't seem to provide anything extra in terms of links (well buttons in their case) to the developer's website:
<img width="1680" alt="Screenshot 2020-11-24 at 16 14 59" src="https://user-images.githubusercontent.com/17980375/100127137-b5708180-2e76-11eb-8ec8-95be6cc017fe.png">

**Comment by lilyvidenova** [comment]
As Im not entirely sure I understand the premise behind us wanting to provide a link to the source code, I have a few questions (that I assume Toto might have the answer to):

- Who are the developers who have requested this feature, I'd love to speak to them to understand it all better? 
- Do we want to provide a way for the developer to make the source + final yaml used for the build + any local assets not remotely accessible downloadable? If we do - are we to provide a way for developers to upload their source code and we host it? 
- Or do we just want to clean up all the links available and style them better?

**Comment by cassiocassio** [comment]
Some questions/ thoughts: What's the motivation behind the request?

Are people wanting to provide links to the source, or to the repo in general? Or to the issues?

Do they want to establish the issues on their repo as the place where conversations happen about their project?

Do they want to show clearly they're open source / that their source is available?

Is it the kind of project where building from source is important for some users / they want to show they have multiple methods of installing?

Are small projects not bothering with a project website, and using their github readme as the frontdoor?

Also relevant for Charms, but when the Snap is not made by the people who make the payload, what the right place to go to?

**Comment by lilyvidenova** [comment]
Thanks, @cassiocassio, I'll add those questions to my list

**Comment by lilyvidenova** [comment]
Caught up with Igor, his comments:


>so i assume that there would be a way for developers to "provide" pointers to their sources in the following ways:
>
>when uploading the snap, they can also optionally manually or automatically upload their sources list (or it is parsed from >snapcraft.yaml)
>there is an option in the dev account to specify the sources used manually
>then for snaps, there would be a drop down list of sources pointers (one or more)
>
>link to any externally accessible repo used, which could be gh, archives, debs, etc
>
>some possible questions/problems:
>
>if sources are freely available but downloaded beforehand and then the snap was built with source dot (.), what then?
>if sources are direct download on random sites, e.g. launchpad or google drive hosting a zip file or an old deb file?
>what if snaps use old out-of-support debs and/or libraries which are necessary for the snap but make no sense out of context, >e.g. libalsa0-oldgit.deb?
>do we want to provide links to repos or any source, including potentially direct downloads (where top-level directory listing is >not possible)?
>do we just want to provide the snapcraft.yaml file, as it already has all the info it?
>do we want to provide local assets, too - e.g. images, libraries etc that are essentially free, but provided by user in a non->public way, e.g.: someone has old ubuntu 12.04 libs on their system, which no longer exist anywhere else?

**Comment by tbille** [comment]
Ok let's reply to some questions:

**@lilyvidenova questions:**

> Who are the developers who have requested this feature, I'd love to speak to them to understand it all better?

This is a request that came from advocacy, @popey I believe

> Do we want to provide a way for the developer to make the source + final yaml used for the build + any local assets not remotely accessible downloadable? If we do - are we to provide a way for developers to upload their source code and we host it?

Here the idea is just to give the ability to share the link of the publisher's repo, we won't ask developers to upload their sources.

> Or do we just want to clean up all the links available and style them better?

Charmhub has something similiar on the details pages: https://app.zeplin.io/project/5f92a9530029eeac84ae9589/screen/5fb25e53d675876aa01d5a7b

See
 ![image.png](https://images.zenhubusercontent.com/583afafbb9dc3c6220228d0c/5e82868f-593e-4cd9-bac7-e2792565a141)


**@cassiocassio questions:**

> What's the motivation behind the request?

We should check again where did the request came from. (@popey ?) 

> Are people wanting to provide links to the source, or to the repo in general? Or to the issues?

The idea here is to link to the repo.

> Do they want to establish the issues on their repo as the place where conversations happen about their project?

 This is already handled by a `contact url` that can be mail or link

> Do they want to show clearly they're open source / that their source is available?

This field would be optional. If someone doesn't want to share the link, because proprietary or because doesn't care then the user should feel free to not share the link.

> Is it the kind of project where building from source is important for some users / they want to show they have multiple methods of installing?

Not sure what to reply here

> Are small projects not bothering with a project website, and using their github readme as the frontdoor?

Agree with this, the website url would be similar to the repo.

> Also relevant for Charms, but when the Snap is not made by the people who make the payload, what the right place to go to?

listing page, snapcraft.yaml (for snaps), metadata.yaml (for charms).


**Igor's questions:**

> if sources are freely available but downloaded beforehand and then the snap was built with source dot (.), what then?

The link to the repo would be a new field added to the metadata.yaml. This follows the discussions that we had during the crossdev catchup about links.
If the link is not provided then we can just not show anything.

> if sources are direct download on random sites, e.g. launchpad or google drive hosting a zip file or an old deb file?

I am not sure what to answer about this. Not sure what is the best solution, to investigate.

> what if snaps use old out-of-support debs and/or libraries which are necessary for the snap but make no sense out of context, >e.g. libalsa0-oldgit.deb?

Not relevant here. This is just sharing the link (gitlab, github, launchapd, bitbucket etc).

> do we want to provide links to repos or any source, including potentially direct downloads (where top-level directory listing is >not possible)?

I think this is part of the investigation of this work. 

> do we just want to provide the snapcraft.yaml file, as it already has all the info it?

No, we would work to get a new link in there.
And I don't think the snapcraft.yaml is relevant here.

> do we want to provide local assets, too - e.g. images, libraries etc that are essentially free, but provided by user in a non->public way, e.g.: someone has old ubuntu 12.04 libs on their system, which no longer exist anywhere else?

Not sure this is relevant here.



I hope this is helpful.

**Comment by popey** [comment]
The request actually came from users, not developers. So a consumer of a snap wants to know the provenance of the software in the snap before installing it. This is something they expect from the `deb` package world. `deb` packages in Ubuntu are typically built in Launchpad, and the source package can be downloaded easily, to enable the user to investigate, and learn from the source. 

A user can do these things in the `apt`/`deb` world and the equivalents in the `snap` world:

"Search for software": `apt search firefox`  | `snap find firefox`
"Get details about an app you find": `apt cache show firefox` | `snap info firefox`
"Download the source for the software": `apt source firefox`

Snap has no equivalent for the last one. For a number of reasons, not least that a snap might be compiled/build on a developer workstation, and no source is uploaded, or in a CI system directly from the source repo - such as in travis or github actions. As such the snap store doesn't "know" where the source came from. This makes it harder for users to 'trust' the application because they can't peer into it.

I am not suggesting the store should hold a source code repo, such they users could `snap source firefox` but simply a link to wherever the source code actually resides. So if they want to investigate, they can. 

In addition, for a developer, publishing applications in the Snap Store, they can provide a link to their repo, which makes it easier for people to get involved in development of the application.

**Comment by lilyvidenova** [comment]
Awesome, thank you @popey and @tbille - super helpful!
