### ISSUE TITLE
snapcraft.io/build via webhook - core18 should imply snapcraft from bionic

### ISSUE THREAD

**Issue by agrrr3** [canonical-web-and-design/snapcraft.io#3443]
### Expected behaviour
If you specify base: core18 in your snapcraft.yaml, the build via webhook is executed using the snapcraft binary from bionic (or at least not with an completely outdated binary).

### Steps to reproduce the problem
Not sure. I was trying to make the build work and suddenly it stopped using bionic and used xenial instead.

Last working revision on https://github.com/agrrr3/freeorion/blob/504faf736cf1a1ac89172042a3a229184d0c0c23/snap/snapcraft.yaml
[launchpad build 1318598 using bionic](https://snapcraft.io/freeorion/builds/1318598)

This (unrelated) commit seems to have broken it https://github.com/agrrr3/freeorion/commit/01533b02bb20b9bdde856c00ec8f0f048412b6bf
Also starting with that build also the architecture: amd64 gets ignored and it builds for all platforms (this could be consistent with using a snapcraft 2.4 in xenial)

[launchpad build 1318603 using xenial](https://snapcraft.io/freeorion/builds/1318603)

Also retriggering a build with the last working revision is broken now. 
[launchpad build 1319782 using xenial](https://snapcraft.io/freeorion/builds/1319782)

### Specs

- _URL:_ [forum.s.io thread](https://forum.snapcraft.io/t/building-snapcraft-io-via-github-weblink-different-snapcraft-binaries/23087/4)

**Comment by agrrr3** [comment]
As I did not get a reaction, I tried to "clean" this by disconnecting the repository and reconnecting it afterwards. It still is broken.

It seems I deleted the referenced build logs by doing that though :/

**Comment by tbille** [comment]
hey @agrrr3 Sorry for the late answer. Let us check what is happening here :)

**Comment by cjwatson** [comment]
Launchpad fetches https://raw.githubusercontent.com/agrrr3/freeorion/HEAD/snap/snapcraft.yaml to work out exactly how to dispatch builds.  But for some reason that URL is giving us the `snap/snapcraft.yaml` from commit 1c5d8994d1671b23275dd99110e793201ff669cf, rather than the one from `master` (indeed, https://raw.githubusercontent.com/agrrr3/freeorion/master/snap/snapcraft.yaml returns the correct contents), despite the fact that `master` is this repository's default branch and that should be what `HEAD` refers to.

It's not clear to me whether GitHub has changed something or whether we're holding it wrong.  Going to raw.githubusercontent.com directly was always a bit of a shortcut to minimize our use of the more expensive (and rate-limited) API, but maybe we can no longer rely on doing that; I'm not sure yet.  At any rate, this is a problem with Launchpad itself rather than with the snapcraft.io frontend, so could you please refile this as a bug on https://bugs.launchpad.net/launchpad?

**Comment by jkfran** [comment]
@cjwatson we had a similar issue with raw.githubusercontent.com were the content was an older version as well, we are now getting the last commit ID from the GitHub API before consuming raw.githubusercontent.com. It might be something similar for you.

I will close the issue here, please open a bug on https://bugs.launchpad.net/launchpad as @cjwatson mentioned.
