### ISSUE TITLE
In admin, if trying to access "ubuntu" store you get a 500 and not a 404

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/snapcraft.io#3512]
Sentry errors:
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/16750/
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/17892/
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/17893/

**Comment by steverydz** [comment]
@jkfran I think this is the case for any store where you don't have the credentials to see it. Can we make it 404 in these cases?

**Comment by jkfran** [comment]
@steverydz Did you speak with them about this? Seems like it's giving a different error on staging:
```
surl -p store_admin -s staging -e francisco.jimenez.cabrera@canonical.com -X GET https://dashboard.staging.snapcraft.io/api/v2/stores/ubuntu/snaps

{"error-list": [{"code": "resource-not-found", "message": "The resource requested does not exist or credentials are not sufficient to access it."}]}%   
```

On production, the API is still having this issue and it's returning a `504 Gateway Time-out` we can't show a 404 because it's an issue on their side. If they fix it then we can return a 404 when it happen

**Comment by steverydz** [comment]
I've sent an email to Natalia regarding this. I'll mark this as blocked for now.
