### ISSUE TITLE
Validation with users (round II) - Progressive releases

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/snapcraft.io#3711]
Schedule and run sessions with: Stephan, Steve, Toto, Robin

[Notes and findings](https://docs.google.com/document/d/1gz8kouK32AyiOHT6ILMMwkcoy1_VRtWuRzrRgofSLpQ/edit#heading=h.djsvypije3ni)

**Comment by danielmutis** [comment]
### Summary of findings:
* Most of the users interviewed prefer using the UI for releases. It makes them feel safer about releasing the right thing to the right channel. 
* All users indicate that they’d like to see this information in the ‘Releases’ tab. 
* The preferred option for the cell is the one which has an arrow that goes from the previous revision towards the progressive one. It gives the users a clear indication of the direction of the release.
  -  Providing percentages in the cell is confusing and all users couldn’t determine whether the percentage was a current, available or target. 
  - The tooltip on the cell is useful and clear in providing detail about what is being released, which release is progressive, and what is the status of the release.
* The preferred option for the channel history is the bar chart with the progress below the chart. This option provided users with a visual way to interpret the information, as well as providing them immediately the precise numbers of the target and progress.
  - All users interpreted the chart correctly, identifying the target, the current percentage of devices, and the bar being 100% of devices.
  - The text immediately available on the page was preferred to the tooltip since the chart doesn’t have any indication of being hoverable. Labels help users identify what each number means, although more familiar users can interpret the information without them.
  - One user was concerned about vertical space, but we considered that not an impediment for the usability of the page.
  - The white rows were clearly identified as being the current revisions being released.
* We decided not to show the progress of the release on full releases, because it can provide confusion as to why it may never reach 100% of the users. Given that we can’t provide information on what revision the missing users may be consuming, we decided to avoid confusion on a feature that isn’t currently being requested.

**Comment by clagom** [comment]
Thanks, good findings. Are we sharing with the Store team?
