### ISSUE TITLE
Snap releases view result in bad gateway

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#3922]
Go to releases page for any snap and see that it results in a bad gateway. For example, https://snapcraft.io/code/releases.

https://sentry.is.canonical.com/canonical/snapcraft-io/issues/25010/?referrer=github_plugin

```
StoreApiConnectionError: Service Unavailable
  File "webapp/publisher/snaps/release_views.py", line 38, in get_release_history
    channel_map = publisher_api.snap_channel_map(flask.session, snap_name)
  File "canonicalwebteam/store_api/publisher.py", line 296, in snap_channel_map
    return self.process_response(response)
  File "canonicalwebteam/store_api/publisher.py", line 21, in process_response
    raise StoreApiConnectionError("Service Unavailable")

BadGateway: 502 Bad Gateway: Service Unavailable
(2 additional frame(s) were not displayed)
...
  File "webapp/decorators.py", line 23, in is_user_logged_in
    return func(*args, **kwargs)
  File "webapp/publisher/snaps/release_views.py", line 42, in get_release_history
    return _handle_error(api_error)
  File "webapp/publisher/views.py", line 62, in _handle_error
    return flask.abort(502, str(api_error))
  File "werkzeug/exceptions.py", line 822, in abort
    return _aborter(status, *args, **kwargs)
  File "werkzeug/exceptions.py", line 807, in __call__
    raise self.mapping[code](*args, **kwargs)

BadGateway: 502 Bad Gateway: Service Unavailable
```

**Comment by jkfran** [comment]
@Roadmaster we are getting 504 errors from `https://dashboard.snapcraft.io/api/v2/snaps/<SNAP>/channel-map `

**Comment by Lukewh** [comment]
Seems to be for a subset of snaps

**Comment by Lukewh** [comment]
@anthonydillon do you have access to snaps in your list of snaps https://snapcraft.io/snaps ?

**Comment by Lukewh** [comment]
OK, so this isn't as critical as it first appears, this error *only* happens if a user isn't a collaborator on a snap. If a normal user (not publisher) directly visits https://snapcraft.io/code/releases, they will receive a 502 – this is incorrect.

What should happen for non-publisher users that attempt to visit publisher pages:
/snapthatdoesntexist/releases -> 404
/snapthatisunlisted/releases -> 404
/snapthatispublic/releases -> /snapthatispublic

**Comment by anthonydillon** [comment]
I would suggest 401 Unauthorized response status code.

**Comment by jkfran** [comment]
I want to be more specific.

Non authenticated users -> redirection to /login (This is working as expected)

**Authenticated users:**

/snapthatdoesntexist/releases -> 404 - Because it doesn't exists it's the right return code
/snapthatisunlisted/releases -> 404 - Because we don't want to disclose snaps that are private/unlisted
/snapthatispublic/releases -> Here is where we can have a discussion. The API is still returning a 404 because they don't want to disclose the snap, however, we know that the snap is there because it is public. I agree with @anthonydillon it should be a 401; however, because the API is not doing it, I think we should return the same response as the API with a 404.
