### ISSUE TITLE
Can not add my email quinn.zhu@formelife.com to my snap as a new member or view the snap

### ISSUE THREAD

**Issue by quinnzhu-formelife** [canonical-web-and-design/snapcraft.io#3993]
interactive-strength-dfu

**Comment by jkfran** [comment]
Hi, could you provide more information? How are you trying to add this email?

**Comment by quinnzhu-formelife** [comment]
https://snapcraft.io/interactive-strength-pulseaudio

https://snapcraft.io/interactive-strength-studio

https://snapcraft.io/interactive-strength-fs0001-kernel

I can not access the snaps for our store. Need to add permissions?


Quinn Zhu
Formelife (Interactive Strength Inc)

**Comment by jkfran** [comment]
@Roadmaster is Formelife a brand store? do you know how to proceed?

**Comment by quinnzhu-formelife** [comment]
![image](https://user-images.githubusercontent.com/93552114/168662120-dfa3771f-2198-4b4e-8823-33f346f0a57b.png)

**Comment by quinnzhu-formelife** [comment]
It may need permission to see the store. I am on the company subscription support list

**Comment by Roadmaster** [comment]
@quinnzhu-formelife Since the snap is in a brand store, it will very likely not be visible in snapcraft.io/interactive-strength-studio since those are public listings.

You may be able to see it in https://snapcraft.io/interactive-strength-studio/listing, but you would need to either be the snap's author (you are not) or a collaborator (you are not, either). You would have to ask one of the snap's current collaborators to add you to this (and other snaps) collaborator list. 

If you continue to have trouble I suggest you file a support ticket at https://support.canonical.com or ask one of your colleagues to file one on your behalf. Github issues are public and so we need to be cautious with your company's information, but in a support case we can provide more specific guidance.

- Daniel
