### ISSUE TITLE
Can't read "Your Month In Snaps" mail.

### ISSUE THREAD

**Issue by popey** [canonical-web-and-design/snapcraft.io#4021]
### Expected behaviour

I should be able to click "See more" in the "Your Month In Snaps" mail and see all my snaps listed in a pop-out web page.

### Steps to reproduce the problem

Got the regular email about performance of my snaps. 
I have lots of snaps published, so not all of them are listed in the email. 
So I click the big green "See more" button (or the "View it in your browser" link at the bottom).

![image](https://user-images.githubusercontent.com/1841272/172628240-52f246eb-6c6c-4b55-b731-dc31c8cd56b1.png)

![image](https://user-images.githubusercontent.com/1841272/172628325-58ee8a4a-4ff2-49cb-ba11-daa4d2d6b39d.png)

It shows an error:

"This email is only viewable in the web viewer when clicking through the original email. To try again, please go back to the email and click "View as Web Page"

![image](https://user-images.githubusercontent.com/1841272/172628805-8432d707-2c3d-4d3f-88c4-8a43fac73aab.png)

1. There is no "View as Web Page" button in the email. (is that assuming I use outlook or something?)
2. The page used to work and no longer does.

### Specs

- _URL:_ https://pages.ubuntu.com/index.php/email/emailWebview?md_id=7662
- _Operating system:_ Kubuntu 22.04
- _Browser:_ Microsoft Edge Version 103.0.1253.0 (Official build) dev (64-bit)

**Comment by jkfran** [comment]
Hi @popey, how long! haha

That link you shared shows an error message because the URL is missing `mkt_tok` in the query string. I can't reproduce the error with mine. The original link on the email should be like this:

```
https://pages.ubuntu.com/index.php/email/emailWebview?mkt_tok=LONGSTRINGHERE&md_id=7662
```

Now it's true that after the first visit, `mkt_tok` is removed from the URL, but I wonder if you have some plugin in your browser that is stripping away this Marketo property before the request is made.

You can try to obtain the URL with `mkt_tok` on it and visit it in a different browser.

**Comment by popey** [comment]
Hey! Thanks for the quick response. You're right, it's my browser and an extension. Sorry for the noise!
